let zigzag = {};
let zigzagdesc = {};
zigzag[0] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[0] = "";

zigzag[1] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[1] = "";

zigzag[2] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[2] = "";

zigzag[3] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[3] = "";

zigzag[4] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[4] = "";

zigzag[5] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[5] = "";

zigzag[6] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[6] = "";

zigzag[7] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[7] = "";

zigzag[8] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[8] = "";

zigzag[9] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[9] = "";

zigzag[10] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[10] = "";

zigzag[11] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[11] = "";

zigzag[12] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[12] = "";

zigzag[13] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[13] = "";

zigzag[14] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[14] = "";

zigzag[15] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[15] = "";

zigzag[16] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[16] = "";

zigzag[17] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[17] = "";

zigzag[18] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[18] = "";

zigzag[19] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[19] = "";

zigzag[20] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[20] = "";

zigzag[21] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[21] = "";

zigzag[22] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[22] = "";

zigzag[23] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[23] = "";

zigzag[24] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[24] = "";

zigzag[25] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[25] = "";

zigzag[26] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[26] = "";

zigzag[27] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td style=\"color: red;\">(21,1/7)</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[27] = "";

zigzag[28] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td style=\"color: red;\">(21,1/7)</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td style=\"color: red;\">(22,8/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[28] = "";

zigzag[29] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td style=\"color: red;\">(21,1/7)</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td style=\"color: red;\">(23,7/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td style=\"color: red;\">(22,8/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[29] = "";

zigzag[30] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td style=\"color: red;\">(21,1/7)</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td style=\"color: black;\">6/3</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td style=\"color: red;\">(23,7/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td style=\"color: red;\">(22,8/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[30] = "";

zigzag[31] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td style=\"color: red;\">(21,1/7)</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td style=\"color: red;\">(24,5/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td style=\"color: black;\">6/3</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td style=\"color: red;\">(23,7/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td style=\"color: red;\">(22,8/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[31] = "";

zigzag[32] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td style=\"color: red;\">(21,1/7)</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td style=\"color: red;\">(25,4/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td style=\"color: red;\">(24,5/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td style=\"color: black;\">6/3</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td style=\"color: red;\">(23,7/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td style=\"color: red;\">(22,8/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[32] = "";

zigzag[33] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td style=\"color: red;\">(21,1/7)</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td style=\"color: black;\">3/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td style=\"color: red;\">(25,4/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td style=\"color: red;\">(24,5/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td style=\"color: black;\">6/3</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td style=\"color: red;\">(23,7/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td style=\"color: red;\">(22,8/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[33] = "";

zigzag[34] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td style=\"color: red;\">(21,1/7)</td><td>...</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td style=\"color: red;\">(26,2/7)</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td style=\"color: black;\">3/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td style=\"color: red;\">(25,4/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td style=\"color: red;\">(24,5/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td style=\"color: black;\">6/3</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td style=\"color: red;\">(23,7/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td style=\"color: red;\">(22,8/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[34] = "";

zigzag[35] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td style=\"color: red;\">(21,1/7)</td><td style=\"color: red;\">(27,1/8)</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td style=\"color: red;\">(26,2/7)</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td style=\"color: black;\">3/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td style=\"color: red;\">(25,4/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td style=\"color: red;\">(24,5/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td style=\"color: black;\">6/3</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td style=\"color: red;\">(23,7/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td style=\"color: red;\">(22,8/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[35] = "";

zigzag[36] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td style=\"color: red;\">(21,1/7)</td><td style=\"color: red;\">(27,1/8)</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td style=\"color: red;\">(26,2/7)</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td style=\"color: black;\">3/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td style=\"color: red;\">(25,4/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td style=\"color: red;\">(24,5/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td style=\"color: black;\">6/3</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td style=\"color: red;\">(23,7/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td style=\"color: red;\">(22,8/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td style=\"color: red;\">(28,9/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[36] = "";

zigzag[37] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td style=\"color: red;\">(21,1/7)</td><td style=\"color: red;\">(27,1/8)</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td style=\"color: red;\">(26,2/7)</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td style=\"color: black;\">3/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td style=\"color: red;\">(25,4/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td style=\"color: red;\">(24,5/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td style=\"color: black;\">6/3</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td style=\"color: red;\">(23,7/2)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td style=\"color: red;\">(22,8/1)</td><td style=\"color: black;\">8/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td style=\"color: red;\">(28,9/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[37] = "";

zigzag[38] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td style=\"color: red;\">(21,1/7)</td><td style=\"color: red;\">(27,1/8)</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td style=\"color: red;\">(26,2/7)</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td style=\"color: black;\">3/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td style=\"color: red;\">(25,4/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td style=\"color: red;\">(24,5/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td style=\"color: black;\">6/3</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td style=\"color: red;\">(23,7/2)</td><td style=\"color: red;\">(29,7/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td style=\"color: red;\">(22,8/1)</td><td style=\"color: black;\">8/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td style=\"color: red;\">(28,9/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[38] = "";

zigzag[39] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td style=\"color: red;\">(21,1/7)</td><td style=\"color: red;\">(27,1/8)</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td style=\"color: red;\">(26,2/7)</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td style=\"color: black;\">3/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td style=\"color: red;\">(25,4/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td style=\"color: red;\">(24,5/4)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td style=\"color: black;\">6/3</td><td style=\"color: black;\">6/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td style=\"color: red;\">(23,7/2)</td><td style=\"color: red;\">(29,7/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td style=\"color: red;\">(22,8/1)</td><td style=\"color: black;\">8/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td style=\"color: red;\">(28,9/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[39] = "";

zigzag[40] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td style=\"color: red;\">(21,1/7)</td><td style=\"color: red;\">(27,1/8)</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td style=\"color: red;\">(26,2/7)</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td style=\"color: black;\">3/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td style=\"color: red;\">(25,4/5)</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td style=\"color: red;\">(24,5/4)</td><td style=\"color: black;\">5/5</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td style=\"color: black;\">6/3</td><td style=\"color: black;\">6/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td style=\"color: red;\">(23,7/2)</td><td style=\"color: red;\">(29,7/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td style=\"color: red;\">(22,8/1)</td><td style=\"color: black;\">8/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td style=\"color: red;\">(28,9/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[40] = "";

zigzag[41] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td style=\"color: red;\">(21,1/7)</td><td style=\"color: red;\">(27,1/8)</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td style=\"color: red;\">(26,2/7)</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td style=\"color: black;\">3/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td style=\"color: red;\">(25,4/5)</td><td style=\"color: black;\">4/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td style=\"color: red;\">(24,5/4)</td><td style=\"color: black;\">5/5</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td style=\"color: black;\">6/3</td><td style=\"color: black;\">6/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td style=\"color: red;\">(23,7/2)</td><td style=\"color: red;\">(29,7/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td style=\"color: red;\">(22,8/1)</td><td style=\"color: black;\">8/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td style=\"color: red;\">(28,9/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[41] = "";

zigzag[42] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td style=\"color: red;\">(21,1/7)</td><td style=\"color: red;\">(27,1/8)</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td style=\"color: red;\">(26,2/7)</td><td>...</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td style=\"color: black;\">3/6</td><td style=\"color: red;\">(30,3/7)</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td style=\"color: red;\">(25,4/5)</td><td style=\"color: black;\">4/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td style=\"color: red;\">(24,5/4)</td><td style=\"color: black;\">5/5</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td style=\"color: black;\">6/3</td><td style=\"color: black;\">6/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td style=\"color: red;\">(23,7/2)</td><td style=\"color: red;\">(29,7/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td style=\"color: red;\">(22,8/1)</td><td style=\"color: black;\">8/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td style=\"color: red;\">(28,9/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[42] = "";

zigzag[43] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td style=\"color: red;\">(21,1/7)</td><td style=\"color: red;\">(27,1/8)</td><td>...</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td style=\"color: red;\">(26,2/7)</td><td style=\"color: black;\">2/8</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td style=\"color: black;\">3/6</td><td style=\"color: red;\">(30,3/7)</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td style=\"color: red;\">(25,4/5)</td><td style=\"color: black;\">4/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td style=\"color: red;\">(24,5/4)</td><td style=\"color: black;\">5/5</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td style=\"color: black;\">6/3</td><td style=\"color: black;\">6/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td style=\"color: red;\">(23,7/2)</td><td style=\"color: red;\">(29,7/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td style=\"color: red;\">(22,8/1)</td><td style=\"color: black;\">8/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td style=\"color: red;\">(28,9/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[43] = "";

zigzag[44] = "<table><tr><td></td><td>b = 1</td><td>b = 2</td><td>b = 3</td><td>b = 4</td><td>b = 5</td><td>b = 6</td><td>b = 7</td><td>b = 8</td><td>b = 9</td></tr><tr><td>a = 1</td><td style=\"color: red;\">(1,1/1)</td><td style=\"color: red;\">(3,1/2)</td><td style=\"color: red;\">(5,1/3)</td><td style=\"color: red;\">(9,1/4)</td><td style=\"color: red;\">(11,1/5)</td><td style=\"color: red;\">(17,1/6)</td><td style=\"color: red;\">(21,1/7)</td><td style=\"color: red;\">(27,1/8)</td><td style=\"color: red;\">(31,1/9)</td></tr><tr><td>a = 2</td><td style=\"color: red;\">(2,2/1)</td><td style=\"color: black;\">2/2</td><td style=\"color: red;\">(8,2/3)</td><td style=\"color: black;\">2/4</td><td style=\"color: red;\">(16,2/5)</td><td style=\"color: black;\">2/6</td><td style=\"color: red;\">(26,2/7)</td><td style=\"color: black;\">2/8</td><td>...</td></tr><tr><td>a = 3</td><td style=\"color: red;\">(4,3/1)</td><td style=\"color: red;\">(7,3/2)</td><td style=\"color: black;\">3/3</td><td style=\"color: red;\">(15,3/4)</td><td style=\"color: red;\">(20,3/5)</td><td style=\"color: black;\">3/6</td><td style=\"color: red;\">(30,3/7)</td><td>...</td><td>...</td></tr><tr><td>a = 4</td><td style=\"color: red;\">(6,4/1)</td><td style=\"color: black;\">4/2</td><td style=\"color: red;\">(14,4/3)</td><td style=\"color: black;\">4/4</td><td style=\"color: red;\">(25,4/5)</td><td style=\"color: black;\">4/6</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 5</td><td style=\"color: red;\">(10,5/1)</td><td style=\"color: red;\">(13,5/2)</td><td style=\"color: red;\">(19,5/3)</td><td style=\"color: red;\">(24,5/4)</td><td style=\"color: black;\">5/5</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 6</td><td style=\"color: red;\">(12,6/1)</td><td style=\"color: black;\">6/2</td><td style=\"color: black;\">6/3</td><td style=\"color: black;\">6/4</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 7</td><td style=\"color: red;\">(18,7/1)</td><td style=\"color: red;\">(23,7/2)</td><td style=\"color: red;\">(29,7/3)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 8</td><td style=\"color: red;\">(22,8/1)</td><td style=\"color: black;\">8/2</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr><tr><td>a = 9</td><td style=\"color: red;\">(28,9/1)</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table>";

zigzagdesc[44] = "";

let NZigzags = 45;
